# NoteBook for the Python Programming language

# 1 Some Basics of Starting Python Programming

# 1.2 Variable assignment

# 1.3 Print fuction

In [1]:
my_name = "shohag"
my_name

'shohag'

In [2]:
print(my_name)

shohag


# 1.4    .format

In [3]:
my_name = "Shohag"
my_age = 34

In [4]:
"I am {} and {} years old guy living in Helsinki, Finland".format(my_name,my_age)

'I am Shohag and 34 years old guy living in Helsinki, Finland'

In [5]:
print("I am {} and {} years old guy living in Helsinki, Finland".format(my_name,my_age))

I am Shohag and 34 years old guy living in Helsinki, Finland


In [6]:
print("I am {one} and {two} years old guy living in Helsinki, Finland".format(one=my_name,two=my_age))

I am Shohag and 34 years old guy living in Helsinki, Finland


# 1.5 Indexing

In [7]:
S = "hello"
S[0]

'h'

In [8]:
S[-1]

'o'

In [9]:
S = "abcdefghijkl"
S[0:]

'abcdefghijkl'

In [10]:
S[:4]

'abcd'

In [11]:
S[0:4]

'abcd'

# 2 List

In [12]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [13]:
# If a list is to be updated by adding any new object then ...
my_list.append("shohag")
my_list

[1, 2, 3, 4, 'shohag']

In [14]:
# If a list is to be updated by replacing an object then...
my_list[4] = "Mirazum"
my_list

[1, 2, 3, 4, 'Mirazum']

In [15]:
# A list can have lists and they are to retrive as following
new_list = [1,2,3,4,5, [4,3,2,1,[100, 200]]]

# We want to slice 100 from the new_list
new_list[5][4][0]

100

# 3 Dictionaries

In [16]:
country_list = {"country1":"Bangladesh", "country2":"India", "country3":"Pakistan"}
country_list

{'country1': 'Bangladesh', 'country2': 'India', 'country3': 'Pakistan'}

In [17]:
country_list["country1"]

'Bangladesh'

In [18]:
 country_list["country3"]

'Pakistan'

In [19]:
new_dictionary = {"k1":{"innerkey":[1,2,3,4]}}
new_dictionary

{'k1': {'innerkey': [1, 2, 3, 4]}}

In [20]:
# Let´s slice 4 from the value of the new_dictionary 
new_dictionary["k1"]["innerkey"][3]

4

# 4 Tuples

In [21]:
my_list = (1,2,3,4)

In [22]:
my_list[2]

3

# 5 Sets

In [23]:
a_set = {1,2,3,2,1,3,2,1,3}
a_set # The out put is the unique number once

{1, 2, 3}

In [24]:
set([1,1,1,1,14,4,4,4,4,4,3,3,3,3,6,6,6,7,7,7,]) # It produces a set of the unique numbers

{1, 3, 4, 6, 7, 14}

In [25]:
a_set

{1, 2, 3}

In [26]:
# An addition with existing set
a_set.add(5)
a_set

{1, 2, 3, 5}

#  6 Comparison Operator

In [27]:
# Examples:

print ((1<3) and (2>5))
print ((1<3) or (2>5))

False
True


In [28]:
print ((1<3) and (2>5) and 10==11)
print ((1<3) or (2>5) or 10==11)

False
True


#  6.1 if, else, elif statements

In [29]:
if 100==101:
    print("100 is equivalent to 101")
else:
    print("100 is not equivalent to 101")

100 is not equivalent to 101


In [30]:
if 2 % 2 == 0:
    print("It is possible")
else:
    print("It is not possible")
    

It is possible


In [31]:
if "shohag" == "mira":
    print("Holly Shit")
elif "shohag" != "mira":
    print("I love you jan")
else:
    print("What!")

I love you jan


# 6.2 for loop, while loop

In [32]:
seq = [1,2,3,4,5]
for number in seq:
    print(number)

1
2
3
4
5


In [33]:
for num in seq:
    print("Hello")

Hello
Hello
Hello
Hello
Hello


In [34]:
i = 1

while i < 5:
    print("Hello")
    i = i+1

Hello
Hello
Hello
Hello


In [35]:
i = 1

while i < 5:
    print(i)
    i = i+1

1
2
3
4


In [36]:
i = 1

while i < 5:
    print("The executed value of i is {}".format(i))
    i = i+1

The executed value of i is 1
The executed value of i is 2
The executed value of i is 3
The executed value of i is 4


In [37]:
i = 1

while i < 5:
    print("The executed value of i is {one}".format(one=i))
    i = i+1

The executed value of i is 1
The executed value of i is 2
The executed value of i is 3
The executed value of i is 4


In [38]:
for num in range(0,7):
    print("My name is Shohag")

My name is Shohag
My name is Shohag
My name is Shohag
My name is Shohag
My name is Shohag
My name is Shohag
My name is Shohag


# 7 Range

In [39]:
ran = range(1,5)

In [40]:
print(ran)

range(1, 5)


In [41]:
list(ran)

[1, 2, 3, 4]

In [42]:
list(range(1,100,5))

[1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96]

In [43]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# 8 List comprehension

In [44]:
a_list = list(range(1,100,9))
a_list

[1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91]

In [45]:
another_list = []

for num in a_list:
    another_list.append(num**2)
    
print(another_list)

[1, 100, 361, 784, 1369, 2116, 3025, 4096, 5329, 6724, 8281]


In [46]:
another_list = [num**2 for num in a_list]
another_list

[1, 100, 361, 784, 1369, 2116, 3025, 4096, 5329, 6724, 8281]

# 9 Function

In [47]:
def name_func(name):
    print("My name is "+ name +".")

name_func("shohag")

My name is shohag.


In [48]:
name_func

<function __main__.name_func(name)>

In [49]:
def sq_func(num):
    return num**2     # Print also can be used but return is more meaningful 

sq_func(10)

100

# 9.1 Function : Documentation String for Function

In [50]:
def my_function(num):
    
    """
    This is known as my_function
    which triples the input number
    """
    return num**3

In [51]:
my_function    # press shift+tab , it will show the info og this function

<function __main__.my_function(num)>

# -------------------------------------------------- Numpy -----------------------------------------------

# 10 Numpy : Python for Data Science

# 10.1 Numpy Arrays

In [52]:
!pip install numpy # Numpy installation 

Invalid requirement: '#'

You are using pip version 19.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [53]:
import numpy as np # Numpy importion 

In [54]:
my_list = [1,2,3] # Python list

# Now lets put this list in np.array

arr = np.array(my_list)
arr # array

array([1, 2, 3])

In [55]:
your_list = [[1,2,3],[4,5,6],[7,8,9]]
your_arr = np.array(your_list)
your_arr    # Two dimensional array with Three Rows and Three Columns

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 10.2 The easiest and shortcut way of making an array : np.arange()

In [56]:
np.arange(0,50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [57]:
# With step size
np.arange(0,50,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

# 10.3 Special array

In [58]:
np.zeros(3)

array([0., 0., 0.])

In [59]:
np.zeros((3,3))  # In this case Tuple is to use

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# 10.4 np.linspace()

In [61]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [62]:
np.linspace(0,4,4)

array([0.        , 1.33333333, 2.66666667, 4.        ])

In [63]:
np.linspace(1,3,3)

array([1., 2., 3.])

# 10.5 Indentity Matrix

np.eye(single digit)

In [64]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 10.6 np.random.rand()

In [65]:
np.random.rand(4) # One dimensional

array([0.23067514, 0.99479965, 0.23157076, 0.50114013])

# 10.7 np.random.randn()

In [66]:
np.random.randn(5) # One dimensional

array([-0.01070667, -0.48974668,  0.03637642, -1.22700098, -0.63854355])

In [67]:
np.random.randn(3,3) # Two dimensional

array([[ 0.58988008,  1.98341082,  0.8603168 ],
       [ 1.07880322, -0.5755783 ,  0.25780314],
       [ 0.79329221,  1.50457052,  2.1182142 ]])

# 10.8 np.random.randint()

In [68]:
np.random.randint(3)

0

In [69]:
np.random.randint(0,10,10)

array([5, 9, 7, 6, 5, 3, 8, 6, 4, 2])

# 10.9 (arrayName).reshape()

In [70]:
arr_one = np.arange(25)
arr_one

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [71]:
# Reshaping of the arr_one

arr_one.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [72]:
type(arr_one)

numpy.ndarray

# 10.10 Minimum and Maximum in an Array 

In [73]:
arr.max()

3

In [74]:
arr_one.max()

24

In [75]:
arr.min()

1

In [76]:
arr_one.min()

0

# 10.11 (arrayName).argmax/.argmin 

In [77]:
arr_ran = np.arange(5,100,9)
arr_ran

array([ 5, 14, 23, 32, 41, 50, 59, 68, 77, 86, 95])

In [78]:
arr_ran.max() # Maximum value

95

In [79]:
# Now lets find the index value of 95
arr_ran.argmax()

10

In [80]:
# Same for Minimum number
arr_ran.min()

5

In [81]:
arr_ran.argmin()

0

# 10.12 (arrayName).shape

In [82]:
arr_ran.shape

(11,)

In [83]:
# Let´s play a bit
arr_one.shape

(25,)

In [84]:
arr_one.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [85]:
arr_one.shape

(25,)

# 10.13 (arrayName).dtype

In [86]:
arr_one.dtype

dtype('int32')

# Also a trick !!!

In [87]:
# Instead of writing the long syntax we also can use this...
from numpy.random import randint
from numpy.random import rand
from numpy.random import randn

# 11 Numpy Indexing and Selection

In [88]:
my_array = np.arange(0,10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
# Indexing
my_array[6]

6

In [90]:
#Slicing
my_array[0:6]

array([0, 1, 2, 3, 4, 5])

In [91]:
# Shortcut !!
my_array[:6]

array([0, 1, 2, 3, 4, 5])

In [92]:
my_array[6:]

array([6, 7, 8, 9])

# 11.1 Broadcasting

In [93]:
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
my_array[:]=100 # Broadcasting
my_array

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [95]:
# Copy of an array
my_array_copy = my_array.copy()
my_array_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

# 11.2 Two dimension slicing

In [96]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
# Slice 8
arr_2d[2][1]

8

In [98]:
# Slice 5,6 chucnk
arr_2d[1][1:3]

array([5, 6])

# 11.3 Bolean array and Slicing

In [99]:
an_array = np.arange (1,50,2)
an_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [100]:
# Now let´s find the numbers bigger tha 11
big_5 = an_array > 5
big_5

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [101]:
# Now, let´s find out the numbers
an_array[big_5]

array([ 7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39,
       41, 43, 45, 47, 49])

In [102]:
three_arr = np.linspace(1,5,30)
three_arr

array([1.        , 1.13793103, 1.27586207, 1.4137931 , 1.55172414,
       1.68965517, 1.82758621, 1.96551724, 2.10344828, 2.24137931,
       2.37931034, 2.51724138, 2.65517241, 2.79310345, 2.93103448,
       3.06896552, 3.20689655, 3.34482759, 3.48275862, 3.62068966,
       3.75862069, 3.89655172, 4.03448276, 4.17241379, 4.31034483,
       4.44827586, 4.5862069 , 4.72413793, 4.86206897, 5.        ])

In [103]:
less_3 = three_arr < 3 # Elements less than 3
less_3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [104]:
# Which elements are less than 3
three_arr[less_3]

array([1.        , 1.13793103, 1.27586207, 1.4137931 , 1.55172414,
       1.68965517, 1.82758621, 1.96551724, 2.10344828, 2.24137931,
       2.37931034, 2.51724138, 2.65517241, 2.79310345, 2.93103448])

In [105]:
# A practice example
    # Make an array of 50 elements and reshape to 5 Rows and 10 Columns
        # And make an array of the chunks of 13,14 and 23,24

arr_50 = np.arange(50).reshape(5,10)
arr_50

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [106]:
arr_50[1:3,3:5]

array([[13, 14],
       [23, 24]])

# 12 Numpy Operations

In [107]:
# Arra + Array is possible with same number of elements. For example : 

arr1 = np.arange(1,11)
arr2= np.arange(2,12)
print(arr1 + arr2)
print(arr2 - arr1)
print(arr1 * arr2)
print(arr2 / arr1)

[ 3  5  7  9 11 13 15 17 19 21]
[1 1 1 1 1 1 1 1 1 1]
[  2   6  12  20  30  42  56  72  90 110]
[2.         1.5        1.33333333 1.25       1.2        1.16666667
 1.14285714 1.125      1.11111111 1.1       ]


# 12.1 Element wise calculation (Array with Scalars)

In [108]:
arr1 * 100

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [109]:
arr1+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [110]:
arr1 / 10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [111]:
arr2 - 100

array([-98, -97, -96, -95, -94, -93, -92, -91, -90, -89])

# 12.3 Universial Array Functions

In [112]:
np.sqrt(arr1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [113]:
np.exp(arr2)

array([7.38905610e+00, 2.00855369e+01, 5.45981500e+01, 1.48413159e+02,
       4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
       2.20264658e+04, 5.98741417e+04])

In [114]:
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [115]:
np.log(arr2)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
       1.94591015, 2.07944154, 2.19722458, 2.30258509, 2.39789527])

# -------------------------Pandas-----------------------------

# Installation

In [116]:
!pip install pandas

You are using pip version 19.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


# Importation

In [117]:
import numpy as np
import pandas as pd

# Discussed Topics/Contents

# 1 Series

In [118]:
my_label = ["a","b","c"] # Label
my_list = [10,20,30] # List
my_arr = np.array(my_list) # Array
my_dic = {"a":10,"b":20,"c":30} # Dictionary

In [119]:
my_series = pd.Series(data = my_list, index = my_label )
my_series

a    10
b    20
c    30
dtype: int64

In [120]:
country = ["Country","Bangladesh", "Finland", "Sweden","Norway"]
capital = ["Capital", "Dhaka", "Helsinki","Stockholm", "Oslo"]

In [121]:
countries = pd.Series(data = capital, index = country)
countries

Country         Capital
Bangladesh        Dhaka
Finland        Helsinki
Sweden        Stockholm
Norway             Oslo
dtype: object

In [122]:
# Without mentioning "data" and "index"
countries = pd.Series(capital, country)
countries

Country         Capital
Bangladesh        Dhaka
Finland        Helsinki
Sweden        Stockholm
Norway             Oslo
dtype: object

In [123]:
series = pd.Series(np.arange(100,200,10))
series

0    100
1    110
2    120
3    130
4    140
5    150
6    160
7    170
8    180
9    190
dtype: int32

In [124]:
# Fuctions passing through
pd.Series(data=[sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

# 2 DataFrame

In [125]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [126]:
np.random.seed(101) # To get same ramdom values

In [127]:
randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [128]:
data = pd.DataFrame(randn(5,4), ["A","B","C","D","E"], ["M","N","O","P"])
data

M         N         O         P
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

# New column in a dataframe

In [129]:
data["New Col"] = data["M"]*data["N"]
data

M         N         O         P   New Col
A  0.302665  1.693723 -1.706086 -1.159119  0.512631
B -0.134841  0.390528  0.166905  0.184502 -0.052659
C  0.807706  0.072960  0.638787  0.329646  0.058930
D -0.497104 -0.754070 -0.943406  0.484752  0.374851
E -0.116773  1.901755  0.238127  1.996652 -0.222074

In [130]:
# In another way
data.NewCol = data.M * data.N
data

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  


M         N         O         P   New Col
A  0.302665  1.693723 -1.706086 -1.159119  0.512631
B -0.134841  0.390528  0.166905  0.184502 -0.052659
C  0.807706  0.072960  0.638787  0.329646  0.058930
D -0.497104 -0.754070 -0.943406  0.484752  0.374851
E -0.116773  1.901755  0.238127  1.996652 -0.222074

# Dropping a Column

In [131]:
data

M         N         O         P   New Col
A  0.302665  1.693723 -1.706086 -1.159119  0.512631
B -0.134841  0.390528  0.166905  0.184502 -0.052659
C  0.807706  0.072960  0.638787  0.329646  0.058930
D -0.497104 -0.754070 -0.943406  0.484752  0.374851
E -0.116773  1.901755  0.238127  1.996652 -0.222074

In [132]:
# Let´s drop column M from the data set

data.drop("M",axis=1) # axis 1 = column, and axis 0 = index 

N         O         P   New Col
A  1.693723 -1.706086 -1.159119  0.512631
B  0.390528  0.166905  0.184502 -0.052659
C  0.072960  0.638787  0.329646  0.058930
D -0.754070 -0.943406  0.484752  0.374851
E  1.901755  0.238127  1.996652 -0.222074

In [133]:
data

M         N         O         P   New Col
A  0.302665  1.693723 -1.706086 -1.159119  0.512631
B -0.134841  0.390528  0.166905  0.184502 -0.052659
C  0.807706  0.072960  0.638787  0.329646  0.058930
D -0.497104 -0.754070 -0.943406  0.484752  0.374851
E -0.116773  1.901755  0.238127  1.996652 -0.222074

In [134]:
# For permanent inplace  (inplace = True)
data.drop("M",axis=1,inplace=True)
data

N         O         P   New Col
A  1.693723 -1.706086 -1.159119  0.512631
B  0.390528  0.166905  0.184502 -0.052659
C  0.072960  0.638787  0.329646  0.058930
D -0.754070 -0.943406  0.484752  0.374851
E  1.901755  0.238127  1.996652 -0.222074

# Dropping Multiple columns

In [135]:
# Let´s drop O, and P columns without inplace
data.drop(["O","P"], axis=1)

N   New Col
A  1.693723  0.512631
B  0.390528 -0.052659
C  0.072960  0.058930
D -0.754070  0.374851
E  1.901755 -0.222074

# Dropping Index

In [136]:
data

N         O         P   New Col
A  1.693723 -1.706086 -1.159119  0.512631
B  0.390528  0.166905  0.184502 -0.052659
C  0.072960  0.638787  0.329646  0.058930
D -0.754070 -0.943406  0.484752  0.374851
E  1.901755  0.238127  1.996652 -0.222074

In [137]:
# Let´s drop index D, and E
data.drop(["D","E"],axis=0)

N         O         P   New Col
A  1.693723 -1.706086 -1.159119  0.512631
B  0.390528  0.166905  0.184502 -0.052659
C  0.072960  0.638787  0.329646  0.058930

# Slicing / Selecting in DataFrame by loc/iloc

In [138]:
data_set = pd.DataFrame(randn(3,3), ["A","B", "C"], 
                        ["Bangladesh", "India", "Pakistan"])
data_set

Bangladesh     India  Pakistan
A   -0.993263  0.196800 -1.136645
B    0.000366  1.025984 -0.156598
C   -0.031579  0.649826  2.154846

In [139]:
# Let´s grap India by using loc
data_set.loc["B","India"]

1.025984152081572

In [140]:
data_set["India"]["B"]

1.025984152081572

In [141]:
# Let´s grap India by using loc
data_set.iloc[1,1]

1.025984152081572

# 2.1 type()

In [142]:
type(data["O"])

pandas.core.series.Series

In [143]:
type(data)

pandas.core.frame.DataFrame

In [144]:
type(data.O)

pandas.core.series.Series

In [145]:
type(data.N)

pandas.core.series.Series

# Conditional Selection : Case of DataFrame

In [146]:
dataset = pd.DataFrame(randn(5,5), 
                       ["Name","Age","Profession", "Location","House"],
                      ["Bangladesh","India", "Pakistan","Nepal", "Srilanka"])

dataset

Bangladesh     India  Pakistan     Nepal  Srilanka
Name         -0.610259 -0.755325 -0.346419  0.147027 -0.479448
Age           0.558769  1.024810 -0.925874  1.862864 -1.133817
Profession    0.610478  0.386030  2.084019 -0.376519  0.230336
Location      0.681209  1.035125 -0.031160  1.939932 -1.005187
House        -0.741790  0.187125 -0.732845 -1.382920  1.482495

In [147]:
# greater than , less than and other conditios in data frame

dataset > 0

Bangladesh  India  Pakistan  Nepal  Srilanka
Name             False  False     False   True     False
Age               True   True     False   True     False
Profession        True   True      True  False      True
Location          True   True     False   True     False
House            False   True     False  False      True

In [148]:
dataset[dataset>0]

Bangladesh     India  Pakistan     Nepal  Srilanka
Name               NaN       NaN       NaN  0.147027       NaN
Age           0.558769  1.024810       NaN  1.862864       NaN
Profession    0.610478  0.386030  2.084019       NaN  0.230336
Location      0.681209  1.035125       NaN  1.939932       NaN
House              NaN  0.187125       NaN       NaN  1.482495

In [149]:
ban = dataset["Bangladesh"] > 0
ban

Name          False
Age            True
Profession     True
Location       True
House         False
Name: Bangladesh, dtype: bool

In [150]:
dataset[ban]

Bangladesh     India  Pakistan     Nepal  Srilanka
Age           0.558769  1.024810 -0.925874  1.862864 -1.133817
Profession    0.610478  0.386030  2.084019 -0.376519  0.230336
Location      0.681209  1.035125 -0.031160  1.939932 -1.005187

# Multiple Conditional Operators

In [151]:
data

N         O         P   New Col
A  1.693723 -1.706086 -1.159119  0.512631
B  0.390528  0.166905  0.184502 -0.052659
C  0.072960  0.638787  0.329646  0.058930
D -0.754070 -0.943406  0.484752  0.374851
E  1.901755  0.238127  1.996652 -0.222074

In [152]:
# Let´s select the value more than 0.5 and less than 1 for N and P

data[(data[["N","P"]]>0.5) & (data[["N","P"]]<1)]


N   O   P  New Col
A NaN NaN NaN      NaN
B NaN NaN NaN      NaN
C NaN NaN NaN      NaN
D NaN NaN NaN      NaN
E NaN NaN NaN      NaN

In [153]:
data[(data[["N","P"]]>0.5) | (data[["N","P"]]<1)]

N   O         P  New Col
A  1.693723 NaN -1.159119      NaN
B  0.390528 NaN  0.184502      NaN
C  0.072960 NaN  0.329646      NaN
D -0.754070 NaN  0.484752      NaN
E  1.901755 NaN  1.996652      NaN

# And & OR operators in Python

In [154]:
True and True

True

In [155]:
False or False

False

In [156]:
data[(data[["N","P"]]>0.5) | (data[["N","P"]]<1)]

N   O         P  New Col
A  1.693723 NaN -1.159119      NaN
B  0.390528 NaN  0.184502      NaN
C  0.072960 NaN  0.329646      NaN
D -0.754070 NaN  0.484752      NaN
E  1.901755 NaN  1.996652      NaN

In [157]:
data[(data[["N","P"]]>0.5) & (data[["N","P"]]<1)]

N   O   P  New Col
A NaN NaN NaN      NaN
B NaN NaN NaN      NaN
C NaN NaN NaN      NaN
D NaN NaN NaN      NaN
E NaN NaN NaN      NaN

# ----------------------------------Index-----------------------

# Index resetting 

In [158]:
dataset

Bangladesh     India  Pakistan     Nepal  Srilanka
Name         -0.610259 -0.755325 -0.346419  0.147027 -0.479448
Age           0.558769  1.024810 -0.925874  1.862864 -1.133817
Profession    0.610478  0.386030  2.084019 -0.376519  0.230336
Location      0.681209  1.035125 -0.031160  1.939932 -1.005187
House        -0.741790  0.187125 -0.732845 -1.382920  1.482495

In [159]:
# Let´s reset the Index
dataset.reset_index() # If we want dataset with reset index then inplace =True

index  Bangladesh     India  Pakistan     Nepal  Srilanka
0        Name   -0.610259 -0.755325 -0.346419  0.147027 -0.479448
1         Age    0.558769  1.024810 -0.925874  1.862864 -1.133817
2  Profession    0.610478  0.386030  2.084019 -0.376519  0.230336
3    Location    0.681209  1.035125 -0.031160  1.939932 -1.005187
4       House   -0.741790  0.187125 -0.732845 -1.382920  1.482495

# String Splitting short-cut  .split()

In [160]:
name = "Shohag Noman Ratul Bishwajit Farhan".split()
name

['Shohag', 'Noman', 'Ratul', 'Bishwajit', 'Farhan']

In [161]:
dataset["Name"] = name
dataset

Bangladesh     India  Pakistan     Nepal  Srilanka       Name
Name         -0.610259 -0.755325 -0.346419  0.147027 -0.479448     Shohag
Age           0.558769  1.024810 -0.925874  1.862864 -1.133817      Noman
Profession    0.610478  0.386030  2.084019 -0.376519  0.230336      Ratul
Location      0.681209  1.035125 -0.031160  1.939932 -1.005187  Bishwajit
House        -0.741790  0.187125 -0.732845 -1.382920  1.482495     Farhan

# Setting Index

In [162]:
dataset.set_index("Name", inplace = True)
dataset

Bangladesh     India  Pakistan     Nepal  Srilanka
Name                                                         
Shohag      -0.610259 -0.755325 -0.346419  0.147027 -0.479448
Noman        0.558769  1.024810 -0.925874  1.862864 -1.133817
Ratul        0.610478  0.386030  2.084019 -0.376519  0.230336
Bishwajit    0.681209  1.035125 -0.031160  1.939932 -1.005187
Farhan      -0.741790  0.187125 -0.732845 -1.382920  1.482495

In [163]:
# If we reset again
dataset.reset_index()

Name  Bangladesh     India  Pakistan     Nepal  Srilanka
0     Shohag   -0.610259 -0.755325 -0.346419  0.147027 -0.479448
1      Noman    0.558769  1.024810 -0.925874  1.862864 -1.133817
2      Ratul    0.610478  0.386030  2.084019 -0.376519  0.230336
3  Bishwajit    0.681209  1.035125 -0.031160  1.939932 -1.005187
4     Farhan   -0.741790  0.187125 -0.732845 -1.382920  1.482495

# ----------------------Missing Data------------------

In [164]:
import numpy as np
import pandas as pd

In [165]:
# Let´s make a dataframe with missing values

x = {"A" : [1,2,np.nan], "B": [1,np.nan,np.nan], "C" : [1,2,3]}

In [166]:
# Dataframe
data = pd.DataFrame(x)
data

A    B  C
0  1.0  1.0  1
1  2.0  NaN  2
2  NaN  NaN  3

# .dropna

In [167]:
data.dropna()

A    B  C
0  1.0  1.0  1

# .fillna

In [168]:
data.fillna(value=1)

A    B  C
0  1.0  1.0  1
1  2.0  1.0  2
2  1.0  1.0  3

In [169]:
# Let´s fill the missing values with the mean of the column
data

A    B  C
0  1.0  1.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [170]:
data["A"].fillna(value=data["A"].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

# -------------------Groupby--------------

In [171]:
import numpy as np
import pandas as pd

In [172]:
company = "Google Google Microsoft Microsoft FaceBook FaceBook".split()
print(company)

person = "Sam Charlie Amy Vanessa Carl Sarah".split()
print(person)

sales = [200, 120, 340, 124, 243, 350]
print(sales)

['Google', 'Google', 'Microsoft', 'Microsoft', 'FaceBook', 'FaceBook']
['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah']
[200, 120, 340, 124, 243, 350]


In [173]:
data = {"Company":company, "Person":person, "Sales":sales}
data

{'Company': ['Google',
  'Google',
  'Microsoft',
  'Microsoft',
  'FaceBook',
  'FaceBook'],
 'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
 'Sales': [200, 120, 340, 124, 243, 350]}

In [174]:
dataframe = pd.DataFrame(data)
dataframe

Company   Person  Sales
0     Google      Sam    200
1     Google  Charlie    120
2  Microsoft      Amy    340
3  Microsoft  Vanessa    124
4   FaceBook     Carl    243
5   FaceBook    Sarah    350

In [175]:
dataframe

Company   Person  Sales
0     Google      Sam    200
1     Google  Charlie    120
2  Microsoft      Amy    340
3  Microsoft  Vanessa    124
4   FaceBook     Carl    243
5   FaceBook    Sarah    350

In [176]:
dataframe.groupby("Company").mean().loc["FaceBook"]

Sales    296.5
Name: FaceBook, dtype: float64

In [177]:
dataframe.groupby("Company").std()

Sales
Company              
FaceBook    75.660426
Google      56.568542
Microsoft  152.735065

In [178]:
dataframe.groupby("Company").count()

Person  Sales
Company                 
FaceBook        2      2
Google          2      2
Microsoft       2      2

In [179]:
dataframe.groupby("Company").describe()

Sales                                                        
          count   mean         std    min     25%    50%     75%    max
Company                                                                
FaceBook    2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
Google      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
Microsoft   2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [180]:
dataframe.groupby("Company").describe().transpose()

Company        FaceBook      Google   Microsoft
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

#                              ------Merging, Joining and Concatenating--------

# Concatenation...

In [181]:
d1 = dataframe.copy()
d1

Company   Person  Sales
0     Google      Sam    200
1     Google  Charlie    120
2  Microsoft      Amy    340
3  Microsoft  Vanessa    124
4   FaceBook     Carl    243
5   FaceBook    Sarah    350

In [182]:
pd.concat([d1,d1,d1]) # It adds the dataframes row wise, by default axis=0 here

Company   Person  Sales
0     Google      Sam    200
1     Google  Charlie    120
2  Microsoft      Amy    340
3  Microsoft  Vanessa    124
4   FaceBook     Carl    243
5   FaceBook    Sarah    350
0     Google      Sam    200
1     Google  Charlie    120
2  Microsoft      Amy    340
3  Microsoft  Vanessa    124
4   FaceBook     Carl    243
5   FaceBook    Sarah    350
0     Google      Sam    200
1     Google  Charlie    120
2  Microsoft      Amy    340
3  Microsoft  Vanessa    124
4   FaceBook     Carl    243
5   FaceBook    Sarah    350

In [183]:
pd.concat([d1,d1,d1], axis = 1) 
# It adds the dataframes column wise when axis = 1

Company   Person  Sales    Company   Person  Sales    Company   Person  \
0     Google      Sam    200     Google      Sam    200     Google      Sam   
1     Google  Charlie    120     Google  Charlie    120     Google  Charlie   
2  Microsoft      Amy    340  Microsoft      Amy    340  Microsoft      Amy   
3  Microsoft  Vanessa    124  Microsoft  Vanessa    124  Microsoft  Vanessa   
4   FaceBook     Carl    243   FaceBook     Carl    243   FaceBook     Carl   
5   FaceBook    Sarah    350   FaceBook    Sarah    350   FaceBook    Sarah   

   Sales  
0    200  
1    120  
2    340  
3    124  
4    243  
5    350

# Merging...

In [184]:
key = "K0 K1 K2 K3".split()
A = "A0 A1 A2 A3".split()
B = "B0 B1 B2 B3".split()
C = "C0 C1 C2 C3".split()
D = "D0 D1 D2 D3".split()

In [185]:
left = {"key":key,"A": A,"B": B}
left

{'key': ['K0', 'K1', 'K2', 'K3'],
 'A': ['A0', 'A1', 'A2', 'A3'],
 'B': ['B0', 'B1', 'B2', 'B3']}

In [186]:
right = {"key": key, "C": C, "D": D}
right

{'key': ['K0', 'K1', 'K2', 'K3'],
 'C': ['C0', 'C1', 'C2', 'C3'],
 'D': ['D0', 'D1', 'D2', 'D3']}

In [187]:
# Now the dataframe
left = pd.DataFrame(left)
right = pd.DataFrame(right)
print(left)
print(right)

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3
  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3


In [188]:
# Merging
pd.merge(left,right, how="inner", on="key")

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

# Joining....

# --------------------- Pandas - Operations-----------------

In [189]:
data = pd.DataFrame({"col1":[1,2,3,4], "col2":[444,555,666,444],
                     "col3":["abc","def","ghi","xyz"]})
data.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

# Unique Method

In [190]:
data["col2"].unique()

array([444, 555, 666], dtype=int64)

In [191]:
# how many unique values
data["col2"].nunique()

3

In [192]:
data[(data["col1"]>2) &( data["col2"]==444)]

col1  col2 col3
3     4   444  xyz

# Apply Method

In [193]:
# 1. Newly created function
def square(x):
    return x**2

data["col1"].apply(square)

0     1
1     4
2     9
3    16
Name: col1, dtype: int64

In [194]:
# Build in function
data["col3"].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [195]:
# Even it can pass lamda 
data["col1"].apply(lambda x : x**2)

0     1
1     4
2     9
3    16
Name: col1, dtype: int64

# Sorting and Ordering

In [196]:
# Sorting

data.sort_values(by="col2")

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

# Null value cheacking

In [197]:
data.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

# pivot_table()

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# ---------------Machine Learning----------------

# Unsupervised Learning (USL)

# K-Nearest Neighbor (KNN)

# ---------------------------------------Applied Deep learning----------------------------

# IBM FREE CLASSES

1)Introduction to Data Science
(https://lnkd.in/fF79bEj)

2)Data Science Tools
(https://lnkd.in/fYf2ZC8)

3)Data Science Methodology
(https://lnkd.in/fY6Kwqd)

4)Statistics 101
(https://lnkd.in/fpgJf7D)

5)Predictive Modeling Fundamentals I
(https://lnkd.in/f9_Y7UZ)

6)Python for Data Science
(https://lnkd.in/fy8E2wH)

7)Data Analysis with Python
(https://lnkd.in/fRQWByd)

8)Data Visualization with Python
(https://lnkd.in/fFu93ME)

9)Machine Learning with Python
(https://lnkd.in/f_7r534)

10)Deep Learning Fundamentals
(https://lnkd.in/fNvPvix)

11)Deep Learning with TensorFlow
(https://lnkd.in/ftfRtvQ)

# IBM : INTRODUCTION TO DATA SCIENCE

1.  Data Science

It is a science to find answer from the data.

Once upon a time there was not sufficient -
- data
- software
- storage

but now we have tonnes of 
- data
- open source of softwares
- cheap and big storage

# IBM : STATISTICS 101